# 工程访问配置
server:
  port: 8083
  servlet:
    context-path: /dataRoomServer

# spring环境配置
spring:
  profiles:
    # 默认使用h2数据库
    active: h2
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    deserialization:
      # 当实体中没有属性的setter方法时是否抛出异常
      FAIL_ON_UNKNOWN_PROPERTIES: false
      # 字符串转允许List，否则导致 @RequestBody List<T> list 类型无法解析
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
  resources:
    # 自springboot 2.5.5之后，该属性已经被废弃，使用web.resources.static-locations代替
    static-locations: classpath:/static/,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/,file:${gc.starter.file.basePath}
  # 静态资源配置
  mvc:
    throw-exception-if-no-handler-found: true
    # 静态资源访问接口前缀
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  web:
    resources:
      static-locations: classpath:/static/,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/,file:${gc.starter.file.basePath}


mybatis-plus:
  # mybatis plus xml配置文件扫描，多个通过分号隔开
  mapper-locations: classpath*:mapper/**/*.xml
  # typeHandler扫描路径，多个通过分号隔开
  type-handlers-package: com.gccloud
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"唯一ID";
      id-type: AUTO
