spring:
  servlet:
    multipart:
      # 配置上传下载文件的最大值
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    # 替换为自己的 MySQL 数据库信息
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/dashboard?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&nullCatalogMeansCurrent=true
    username: root
    password: pwd

gc:
  starter:
    file:
      # 一个存储文件的绝对路径，需要有写入权限
      basePath: ${user.dir}/dataRoomResource
      uiPath: ./dataRoom-ui
      # 启动服务的访问地址
      urlPrefix: http://127.0.0.1:${server.port}${server.servlet.context-path}/static/
    captcha:
      enable: true
    jwt:
      # 密钥，每个系统一定要自己修改下
      secret: vT9~lW1^
      alg: HS256
      issuer: gc
    dataroom:
      users:
        - username: admin
          userId: 1
          password: kdgc@2025
          role:
            - dataRoomWrite
            - dataRoomRead
        - username: user
          userId: 2
          password: user@2025
          role:
            - dataRoomRead
