spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/dataroom_plus?currentSchema=public&rewriteBatchedStatements=true
    username: root
    password: 123456